/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness probe */
    get: operations["getHealth"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/readyz": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness probe (checks database) */
    get: operations["getReady"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/signup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register a new operator account */
    post: operations["signup"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log in with email and password */
    post: operations["login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Exchange a refresh token for a new token pair */
    post: operations["refresh"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Revoke a refresh token */
    post: operations["logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/password/reset-request": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request a password reset email (always returns 200) */
    post: operations["requestPasswordReset"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/password/reset-confirm": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Set a new password using a reset token */
    post: operations["confirmPasswordReset"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/account/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the authenticated user's profile */
    get: operations["getMe"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update the authenticated user's profile */
    patch: operations["updateMe"]
    trace?: never
  }
  "/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the authenticated operator's events */
    get: operations["listEvents"]
    put?: never
    /** Create an event */
    post: operations["createEvent"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/events/{eventID}": {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    /** Get one event */
    get: operations["getEvent"]
    put?: never
    post?: never
    /** Soft delete an event */
    delete: operations["deleteEvent"]
    options?: never
    head?: never
    /** Update event fields */
    patch: operations["updateEvent"]
    trace?: never
  }
  "/events/{eventID}/archive": {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Archive an event */
    post: operations["archiveEvent"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/events/{eventID}/settings": {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    /** Get an event's gallery settings */
    get: operations["getEventSettings"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update an event's gallery settings */
    patch: operations["updateEventSettings"]
    trace?: never
  }
  "/events/{eventID}/dashboard": {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    /** Get an event's dashboard aggregates */
    get: operations["getEventDashboard"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/events/{eventID}/uploads": {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Initialize a photo upload and receive presigned URL(s) */
    post: operations["initializeUpload"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/uploads/{photoID}": {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    /** Poll the status of an upload (for resume/recovery) */
    get: operations["getUploadStatus"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/uploads/{photoID}/parts": {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Get presigned URLs for multipart part numbers */
    post: operations["getUploadPartURLs"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/uploads/{photoID}/multipart/complete": {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete a multipart upload with the uploaded part ETags */
    post: operations["completeMultipartUpload"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/uploads/{photoID}/multipart/abort": {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Abort a multipart upload */
    post: operations["abortMultipartUpload"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/uploads/{photoID}/complete": {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Verify the uploaded object and mark the photo ready for processing */
    post: operations["completeUpload"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/public/events/{slug}": {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
      }
      cookie?: never
    }
    /**
     * Get a public event by slug (no auth)
     * @description Returns public metadata for a visible event. Private, soft-deleted, or
     *     expired events return 404 (existence is not revealed). Password events
     *     return metadata only after unlock; without a valid token the response
     *     indicates that unlock is required.
     */
    get: operations["getPublicEvent"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/public/events/{slug}/unlock": {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Unlock a password-protected gallery */
    post: operations["unlockPublicEvent"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/public/events/{slug}/photos": {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
      }
      cookie?: never
    }
    /**
     * Cursor-paginated listing of READY photos
     * @description Returns metadata only; image URLs are not embedded. Fetch a signed URL
     *     per photo and variant from the `/url` endpoint. Only `READY` photos are
     *     listed.
     */
    get: operations["listPublicPhotos"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/public/events/{slug}/photos/{photoID}": {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    /** Get one READY photo's metadata */
    get: operations["getPublicPhoto"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/public/events/{slug}/photos/{photoID}/url": {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    /**
     * Get a short-lived signed URL for a photo variant
     * @description Returns a presigned GET URL valid for `SIGNED_URL_TTL` (default 5
     *     minutes). `original` requires `allow_original_download`; any download
     *     requires `allow_download`. Responses are never cached.
     */
    get: operations["getPublicPhotoURL"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    SignupRequest: {
      /** Format: email */
      email: string
      password: string
      businessName?: string
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    AuthResponse: {
      accessToken: string
      refreshToken: string
      expiresIn: number
      user: components["schemas"]["Profile"]
    }
    Profile: {
      /** Format: uuid */
      id: string
      email: string
      businessName?: string
    }
    AuthEnvelope: {
      data?: components["schemas"]["AuthResponse"]
      error?: null | components["schemas"]["Error"]
    }
    ProfileEnvelope: {
      data?: components["schemas"]["Profile"]
      error?: null | components["schemas"]["Error"]
    }
    Envelope: {
      data?: unknown
      error?: null | components["schemas"]["Error"]
    }
    Error: {
      code: string
      message: string
    }
    /** @enum {string} */
    EventStatus: "upcoming" | "active" | "completed" | "archived"
    /** @enum {string} */
    EventVisibility: "public" | "password" | "private"
    Event: {
      /** Format: uuid */
      id: string
      name: string
      slug: string
      clientName?: string
      clientEmail?: string
      location?: string
      description?: string
      /** Format: date */
      eventDate: string | null
      status: components["schemas"]["EventStatus"]
      /** Format: uuid */
      coverPhotoId?: string | null
      /** Format: int64 */
      storageBytes: number
      /** Format: int64 */
      photoCount: number
      /** Format: int64 */
      guestCount: number
      /** Format: date-time */
      expiresAt: string | null
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    EventSettings: {
      /** Format: uuid */
      eventId: string
      visibility: components["schemas"]["EventVisibility"]
      passwordProtected: boolean
      allowDownload: boolean
      allowOriginalDownload: boolean
      watermarkEnabled: boolean
      /** Format: date-time */
      updatedAt: string
    }
    EventSettingsInput: {
      visibility?: components["schemas"]["EventVisibility"]
      /** @description Set a gallery password; empty string clears it */
      password?: string
      allowDownload?: boolean
      allowOriginalDownload?: boolean
      watermarkEnabled?: boolean
    }
    CreateEventRequest: {
      name: string
      /** Format: date */
      eventDate?: string
      clientName?: string
      /** Format: email */
      clientEmail?: string
      location?: string
      description?: string
      status?: components["schemas"]["EventStatus"]
      /** Format: date-time */
      expiresAt?: string
      settings?: components["schemas"]["EventSettingsInput"]
    }
    UpdateEventRequest: {
      name?: string
      /**
       * Format: date
       * @description Empty string clears the date
       */
      eventDate?: string
      clientName?: string
      /** Format: email */
      clientEmail?: string
      location?: string
      description?: string
      /**
       * Format: date-time
       * @description Empty string clears the expiry
       */
      expiresAt?: string
    }
    UpdateEventSettingsRequest: components["schemas"]["EventSettingsInput"]
    EventDashboard: {
      /** Format: int64 */
      photoCount: number
      /** Format: int64 */
      storageBytes: number
      /** Format: int64 */
      guestCount: number
    }
    EventEnvelope: {
      data?: components["schemas"]["Event"]
      error?: null | components["schemas"]["Error"]
    }
    EventWithSettings: {
      event: components["schemas"]["Event"]
      settings: components["schemas"]["EventSettings"]
    }
    EventWithSettingsEnvelope: {
      data?: components["schemas"]["EventWithSettings"]
      error?: null | components["schemas"]["Error"]
    }
    EventList: {
      items: components["schemas"]["Event"][]
      nextCursor: string | null
    }
    EventListEnvelope: {
      data?: components["schemas"]["EventList"]
      error?: null | components["schemas"]["Error"]
    }
    EventSettingsEnvelope: {
      data?: components["schemas"]["EventSettings"]
      error?: null | components["schemas"]["Error"]
    }
    EventDashboardEnvelope: {
      data?: components["schemas"]["EventDashboard"]
      error?: null | components["schemas"]["Error"]
    }
    /** @enum {string} */
    PhotoStatus: "UPLOADING" | "PROCESSING" | "READY" | "FAILED"
    /** @enum {string} */
    UploadKind: "simple" | "multipart"
    InitializeUploadRequest: {
      filename: string
      /** @enum {string} */
      contentType: "image/jpeg" | "image/png" | "image/webp"
      /** Format: int64 */
      size: number
    }
    InitializeUpload: {
      /** Format: uuid */
      photoId?: string
      uploadKind?: components["schemas"]["UploadKind"]
      /** @description Presigned PUT URL (simple uploads). Null for multipart. */
      uploadUrl?: string
      storageKey?: string
      /** Format: date-time */
      expiresAt?: string
      /**
       * Format: int64
       * @description Required part size for multipart uploads.
       */
      partSize?: number | null
    }
    InitializeUploadEnvelope: {
      data?: components["schemas"]["InitializeUpload"]
      error?: null | components["schemas"]["Error"]
    }
    UploadPartURLsRequest: {
      partNumbers: number[]
    }
    PartURL: {
      partNumber?: number
      url?: string
    }
    UploadPartURLs: {
      /** Format: uuid */
      photoId?: string
      /** Format: int64 */
      partSize?: number
      parts?: components["schemas"]["PartURL"][]
    }
    UploadPartURLsEnvelope: {
      data?: components["schemas"]["UploadPartURLs"]
      error?: null | components["schemas"]["Error"]
    }
    CompletedPart: {
      partNumber: number
      etag: string
    }
    CompleteMultipartRequest: {
      parts: components["schemas"]["CompletedPart"][]
    }
    UploadStatus: {
      /** Format: uuid */
      photoId?: string
      /** Format: uuid */
      eventId?: string
      status?: components["schemas"]["PhotoStatus"]
      uploadKind?: components["schemas"]["UploadKind"]
      filename?: string
      mimeType?: string
      /** Format: int64 */
      fileSize?: number
      errorMessage?: string | null
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    UploadStatusEnvelope: {
      data?: components["schemas"]["UploadStatus"]
      error?: null | components["schemas"]["Error"]
    }
    /**
     * @description `thumbnail`, `medium`, `large` are generated derivatives; `original` is
     *     the uploaded file and is gated by `allow_original_download`.
     * @enum {string}
     */
    PhotoVariant: "thumbnail" | "medium" | "large" | "original"
    PublicEvent: {
      name?: string
      /** Format: date */
      date?: string | null
      location?: string
      description?: string
      visibility?: components["schemas"]["EventVisibility"]
      allowDownload?: boolean
      allowOriginalDownload?: boolean
      /** Format: int64 */
      photoCount?: number
      /** Format: uuid */
      coverPhotoId?: string | null
      /** @description True when the event is password-protected and no valid unlock token was supplied. */
      requiresUnlock?: boolean
    }
    PublicEventEnvelope: {
      data?: components["schemas"]["PublicEvent"]
      error?: null | components["schemas"]["Error"]
    }
    UnlockRequest: {
      password: string
    }
    UnlockResult: {
      /** @description Event-scoped unlock token; send via the `X-Gallery-Unlock` header. */
      token?: string
      /** @description Token lifetime in seconds. */
      expiresIn?: number
    }
    UnlockResultEnvelope: {
      data?: components["schemas"]["UnlockResult"]
      error?: null | components["schemas"]["Error"]
    }
    /** @description Metadata only; image URLs are fetched per variant from the `/url` endpoint. */
    PublicPhoto: {
      /** Format: uuid */
      id?: string
      width?: number | null
      height?: number | null
      /** @description Derivative variants available for download. */
      variants?: components["schemas"]["PhotoVariant"][]
    }
    PublicPhotoEnvelope: {
      data?: components["schemas"]["PublicPhoto"]
      error?: null | components["schemas"]["Error"]
    }
    PublicPhotoList: {
      event?: components["schemas"]["PublicEvent"]
      photos?: {
        items?: components["schemas"]["PublicPhoto"][]
        nextCursor?: string | null
      }
    }
    PublicPhotoListEnvelope: {
      data?: components["schemas"]["PublicPhotoList"]
      error?: null | components["schemas"]["Error"]
    }
    SignedURL: {
      /** @description Short-lived presigned GET URL. Never cached or logged. */
      url?: string
      /** @description URL lifetime in seconds. */
      expiresIn?: number
    }
    SignedURLEnvelope: {
      data?: components["schemas"]["SignedURL"]
      error?: null | components["schemas"]["Error"]
    }
  }
  responses: never
  parameters: {
    EventID: string
    /** @description URL slug of the event, unique per operator. */
    EventSlug: string
    /**
     * @description Event-scoped unlock token returned by `/public/events/{slug}/unlock`.
     *     Required for `password` events; ignored for `public` events.
     */
    UnlockToken: string
    PhotoID: string
    /** @description Client-supplied key; repeating it with the same body returns the original result. */
    IdempotencyKey: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is alive */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getReady: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is ready */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Service is not ready */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  signup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"]
      }
    }
    responses: {
      /** @description Account created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AuthEnvelope"]
        }
      }
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Authenticated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AuthEnvelope"]
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Account locked */
      423: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          refreshToken: string
        }
      }
    }
    responses: {
      /** @description New tokens issued */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AuthEnvelope"]
        }
      }
      /** @description Invalid, expired, or reused refresh token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": {
          refreshToken?: string
        }
      }
    }
    responses: {
      /** @description Logged out */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  requestPasswordReset: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string
        }
      }
    }
    responses: {
      /** @description Request accepted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  confirmPasswordReset: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          token: string
          password: string
        }
      }
    }
    responses: {
      /** @description Password reset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Invalid or expired reset token */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProfileEnvelope"]
        }
      }
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  updateMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          businessName?: string
        }
      }
    }
    responses: {
      /** @description Updated profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProfileEnvelope"]
        }
      }
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  listEvents: {
    parameters: {
      query?: {
        status?: components["schemas"]["EventStatus"]
        /** @description Case-insensitive search on the event name */
        q?: string
        /** @description Opaque keyset cursor returned as nextCursor */
        cursor?: string
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of events */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventListEnvelope"]
        }
      }
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Invalid status or cursor */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  createEvent: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEventRequest"]
      }
    }
    responses: {
      /** @description Event created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventWithSettingsEnvelope"]
        }
      }
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Active event limit reached */
      402: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The event */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventEnvelope"]
        }
      }
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Event not found (also for other tenants) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  deleteEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Event not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  updateEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateEventRequest"]
      }
    }
    responses: {
      /** @description Updated event */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventEnvelope"]
        }
      }
      /** @description Event not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  archiveEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Archived event */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventEnvelope"]
        }
      }
      /** @description Event not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Invalid status transition */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getEventSettings: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Event settings */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventSettingsEnvelope"]
        }
      }
      /** @description Event not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  updateEventSettings: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateEventSettingsRequest"]
      }
    }
    responses: {
      /** @description Updated settings */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventSettingsEnvelope"]
        }
      }
      /** @description Event not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getEventDashboard: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Dashboard aggregates */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventDashboardEnvelope"]
        }
      }
      /** @description Event not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  initializeUpload: {
    parameters: {
      query?: never
      header?: {
        /** @description Client-supplied key; repeating it with the same body returns the original result. */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"]
      }
      path: {
        eventID: components["parameters"]["EventID"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InitializeUploadRequest"]
      }
    }
    responses: {
      /** @description Upload initialized */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InitializeUploadEnvelope"]
        }
      }
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Event not found (also for other tenants) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Idempotency key reused with a different request body */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error (unsupported type, too large) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getUploadStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Upload status */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UploadStatusEnvelope"]
        }
      }
      /** @description Photo not found (also for other tenants) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getUploadPartURLs: {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadPartURLsRequest"]
      }
    }
    responses: {
      /** @description Presigned part URLs */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UploadPartURLsEnvelope"]
        }
      }
      /** @description Photo not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Photo is not a multipart upload */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  completeMultipartUpload: {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteMultipartRequest"]
      }
    }
    responses: {
      /** @description Multipart upload completed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Photo not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Photo is not a multipart upload */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  abortMultipartUpload: {
    parameters: {
      query?: never
      header?: never
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Aborted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Photo not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Photo is not a multipart upload */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  completeUpload: {
    parameters: {
      query?: never
      header?: {
        /** @description Client-supplied key; repeating it with the same body returns the original result. */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"]
      }
      path: {
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Upload completed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UploadStatusEnvelope"]
        }
      }
      /** @description Photo or object not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Idempotency conflict or invalid upload state */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Object size mismatch */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getPublicEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Public event metadata */
      200: {
        headers: {
          /**
           * @description `public, max-age=60` for public events; `private, no-store` for
           *     password events.
           */
          "Cache-Control"?: string
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PublicEventEnvelope"]
        }
      }
      /** @description Event not found, private, deleted, or expired */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  unlockPublicEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnlockRequest"]
      }
    }
    responses: {
      /** @description Correct password; event-scoped unlock token issued */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UnlockResultEnvelope"]
        }
      }
      /** @description Incorrect password */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Event not found, private, deleted, or expired */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  listPublicPhotos: {
    parameters: {
      query?: {
        /** @description Opaque keyset cursor returned as nextCursor */
        cursor?: string
        limit?: number
      }
      header?: {
        /**
         * @description Event-scoped unlock token returned by `/public/events/{slug}/unlock`.
         *     Required for `password` events; ignored for `public` events.
         */
        "X-Gallery-Unlock"?: components["parameters"]["UnlockToken"]
      }
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of public photos */
      200: {
        headers: {
          /**
           * @description `public, max-age=60` for public events; `private, no-store` for
           *     password events.
           */
          "Cache-Control"?: string
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PublicPhotoListEnvelope"]
        }
      }
      /** @description Password event requires a valid unlock token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Event not found, private, deleted, or expired */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Invalid cursor or limit */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getPublicPhoto: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description Event-scoped unlock token returned by `/public/events/{slug}/unlock`.
         *     Required for `password` events; ignored for `public` events.
         */
        "X-Gallery-Unlock"?: components["parameters"]["UnlockToken"]
      }
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Public photo metadata */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PublicPhotoEnvelope"]
        }
      }
      /** @description Password event requires a valid unlock token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Event or photo not found, or photo not READY */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
  getPublicPhotoURL: {
    parameters: {
      query: {
        variant: components["schemas"]["PhotoVariant"]
      }
      header?: {
        /**
         * @description Event-scoped unlock token returned by `/public/events/{slug}/unlock`.
         *     Required for `password` events; ignored for `public` events.
         */
        "X-Gallery-Unlock"?: components["parameters"]["UnlockToken"]
      }
      path: {
        /** @description URL slug of the event, unique per operator. */
        slug: components["parameters"]["EventSlug"]
        photoID: components["parameters"]["PhotoID"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Signed URL */
      200: {
        headers: {
          /** @description Always `private, no-store` (URL carries credentials). */
          "Cache-Control"?: string
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SignedURLEnvelope"]
        }
      }
      /** @description Password event requires a valid unlock token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Downloads disabled or original download disabled */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Event or photo not found, or photo not READY */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
      /** @description Invalid variant */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Envelope"]
        }
      }
    }
  }
}
